
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_cafe_api
    command: uvicorn app.main:app --host ${FASTAPI_HOST} --port ${FASTAPI_PORT} --reload
    volumes:
      - ./:/app:cached
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      # API_KEY: ${API_KEY}
      # LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: fastapi_cafe_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
